spring:
  #dubbo 中服务名称
  dubbo:
    application: user-web
    config-center:
      timeout: 40000
    #dubbo的通讯协议名称
    protocol:
      name: dubbo
    #dubbod 的服务扫描路径
    base-package: com.tff.gmall
    registry:
      #zookeeper的注册中心地址
      address: zookeeper://182.92.93.41:2181
      #zookeeper的通讯协议名称
      protocol: zookeeper
    #设置服务调用的超时时间
    consumer:
      timeout: 60000
      #设置是否检查服务存在
      check: false
server:
  port: 8000
