spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gmall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  #dubbo 中服务名称
  dubbo:
    application: manger-service
    #dubbo的通讯协议名称
    protocol:
      name: dubbo
    #dubbod 的服务扫描路径
    base-package: com.tff.gmall
    registry:
      #zookeeper的注册中心地址
      address: zookeeper://182.92.93.41:2181
      #zookeeper的通讯协议名称
      protocol: zookeeper

server:
  port: 8082
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  identity: MYSQL
#dubbo的配置
#1. spring.dubbo.application=
#2. spring.dubbo.protocol.name=
#3. spring.dubbo.registry.proticol=
#4. spring.dubbo.registry.address=
#5. spring.dubbo.registry.protocol=